### ISSUE TITLE
[FE] 공통 컴포넌트 작업

### ISSUE THREAD

**Issue by saejinpark** [codesquad-issue-team-05/issue-tracker-max#7]
# [FE] 공통 컴포넌트 구현

## 공통 컴포넌트 목록
- [x] Button
- [x] TextInput
- [x] ColorCodeInput
- [x] TabButton
- [x] InformationTag
- [x] ProgressIndicator
- [x] DropdownIndicator
- [x] DropdownPanel
- [x] TextArea
- [x] Sidebar
- [x] CommentElement
- [x] FilterBar

**Comment by silvertae** [comment]
Test용 코멘트 입니다.

**Comment by silvertae** [comment]
### Styled-components 스타일 확장시 styled component가 아닌 일반 리액트 컴포넌트를 `styled()`의 인자로 전달할 때 스타일이 제대로 적용되지 않는 문제

-> Styled component로 만들어지지 않은 다른 일반적인 컴포넌트를 인자로 넣어 스타일 확장시에는 해당 컴포넌트에서 `className` prop이 필수!

참고) https://styled-components.com/docs/basics#styling-any-component
